version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ap-northeast-2)
      - npm install yarn
  build:
    commands:
      - echo Build started on `date`
      - echo START BUILD
      - docker build -t ecr-admin-system:latest ./
      - docker tag ecr-admin-system:latest 444773787018.dkr.ecr.ap-northeast-2.amazonaws.com/ecr-admin-system:latest
      - docker push 444773787018.dkr.ecr.ap-northeast-2.amazonaws.com/ecr-admin-system:latest
  post_build:
    commands:
      - echo Post Build completed on `date`
artifacts:
  files:
    - .conf/imagedefinitions.json
  discard-paths: yes